### ISSUE TITLE
how to open reader mode?

### ISSUE THREAD

**Issue by uice** [khuedoan98/one-line-firefox#3]
I can't find reader icon in address bar. So I can't use reader mode in firefox

**Comment by khuedoan** [comment]
Sorry for the late response, because I don't use it so I hide it, you can unhide it by removing [the following lines](https://github.com/khuedoan98/one-line-firefox/blob/d0d3862dfd86b5bab42b5bcd2e61e1c468c3c379/userChrome.css#L54):

```css
#page-action-buttons {
    display: none !important;
}
```
